### ISSUE TITLE
max-rps crash panic: index out of range

### ISSUE THREAD

**Issue by howardjohn** [BuoyantIO/strest-grpc#62]
I run into this pretty consistently with `max-rps`

```
$ strest-grpc max-rps
panic: runtime error: index out of range

goroutine 475 [running]:
github.com/buoyantio/strest-grpc/max-rps.Config.Run.func2(0x0, 0x0, 0x0, 0xc000a0d920, 0x3, 0x3, 0x40593b, 0xc0005a68a0, 0xc0002377a0)
        /Users/zaharidichev/workspace/Go/src/github.com/buoyantio/strest-grpc/max-rps/max-rps.go:81 +0x236
gonum.org/v1/gonum/optimize.evaluate(0xc00012ff20, 0xc0005a92c0, 0x30, 0xc000a0d920, 0x3, 0x3)
        /Users/zaharidichev/workspace/Go/pkg/mod/gonum.org/v1/gonum@v0.0.0-20190221132855-8ea67971a689/optimize/minimize.go:480 +0x135
gonum.org/v1/gonum/optimize.minimize.func3()
        /Users/zaharidichev/workspace/Go/pkg/mod/gonum.org/v1/gonum@v0.0.0-20190221132855-8ea67971a689/optimize/minimize.go:309 +0xf0
created by gonum.org/v1/gonum/optimize.minimize
        /Users/zaharidichev/workspace/Go/pkg/mod/gonum.org/v1/gonum@v0.0.0-20190221132855-8ea67971a689/optimize/minimize.go:316 +0x32b
```

Version 0.0.8

**Comment by jinq0123** [comment]
Me too.

**Comment by kleimkuhler** [comment]
#64 has just merged and fixed this issue for me.

I'm closing this for now, but please feel free to reopen if it still is throwing this error for either of you and I can look at it more.
